spring.application.name=springboot-caching

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=caching
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.connection-timeout=3000
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.pool-name=ServiceConnPool
spring.datasource.connection-test-query="select 1"

# Hibernate (optional, if using JPA)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true