spring.application.name=notification-service
server.port=9060

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=kafka
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.connection-timeout=3000
spring.datasource.maximum-pool-size=100
spring.datasource.minimum-idel=10
spring.datasource.pool-name=ServiceConnPool
spring.datasource.connection-test-query="select 1"

# Hibernate (optional, if using JPA)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Kafka Config
kafka.topic.order-service=order-topic