spring.application.name=spring-security

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/spring-security?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.connection-timeout=3000
spring.datasource.maximum-pool-size=100
spring.datasource.minimum-idel=10
spring.datasource.pool-name=ServiceConnPool
spring.datasource.connection-test-query="select 1"

# Hibernate (optional, if using JPA)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


# Running '.sql' file while start project
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

spring.security.user.name=admin
#spring.security.user.password=$2a$12$jBPqt9KHdQa3NBq0AfcifefreRAIhA.Keeigtp9vpAFii5RB51bnm
spring.security.user.password=password

jwt.secretKey=hdi2qyhe127yhsiu12yw7e12yhwi1h2e

server.session.limit=2
